baseURL = 'https://www.alieundimz.live'
languageCode = 'en-us'
title = 'Alieu Ndimbalane'
theme = "cactus"
copyright = "Alieu Ndimbalane"
enableRobotsTXT = false
# Google Analytics 4
GoogleAnalyticsID = "G-8BLDQJZ598"
googleAnalytics = "G-8BLDQJZ598"
# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Writings"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "About Me"
url = "/about"
weight = 4

[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = false
    noClasses = true
    style = "dracula"
    tabWidth = 4

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5


[params]

  colortheme = "white" # dark, light, white, or classic
  rss = true # generate rss feed. default value is false
  googleAnalyticsAsync = true # use asynchronous tracking. Synchronous tracking by default
  showAllPostsArchive = true # default

  # Home page settings
  description = "I'm a software developer from The Gambia. I specialize in building full stack applications with more focus on the backend. Over the past couple of years, I have worked on some projects that I have open sourced. I have also picked up on writing tutorials and guides. I have over 3 years of professional experience building applications for both the frontend and backend."
  mainSection = "about" # your main section
  showAllPostsOnHomePage = false # default
  postsOnHomePage = 5 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = true # show tags overview by default.
  showProjectsList = true # show projects list by default (if projects data file exists).
  projectsUrl = "https://github.com/ndimzKM" # title link for projects list

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "" # default

  # Post page settings
  show_updated = true # default
  showReadTime = true # default

  [params.comments]
    enabled = false # default
    engine = "cactus_comments" # only disqus, utterances, and cactus_comments is supported
    [params.comments.utterances]
      repo = "<github_username>/<github_reponame>"
      label = "hugo-site-name" # you can use however you want to label your name in your repo's issues
      theme = "github-light"
    [params.comments.cactuscomments]
      siteName = "your_cactus_comments_sitename" # see https://cactus.chat/ on how to register your site name
      #serverUrl = "" # Defaults to https://matrix.cactus.chat:8448 (Cactus Chat public server)
      #serverName = "" # Defaults to cactus.chat

  # the value of name should be an valid font awesome icon name (brands type)
  # https://fontawesome.com/icons?d=gallery&s=brands
  [[params.social]]
    name = "github"
    link = "https://github.com/ndimzKM"
  [[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/alieundimbalane"
  [[params.social]]
    name = "email"
    link = "alieundimbalane@gmail.com"  # no need for "mailto:" in the head
